### ISSUE TITLE
error in codec section?

### ISSUE THREAD

**Issue by victorhck** [cb400f/opensuse-guide.org#1]
Hi !

Today doing a review, I found in the codec section that it's suggested to add this repo:
`zypper addrepo -f http://opensuse-guide.org/repo/openSUSE_Leap_42.2/ dvd`
it's really the right link? Do you have a dvd repo in your server?

BTW I see that you have updated your guide! Then I have to do the same in the spanish one! ;)

've phun!

**Comment by victorhck** [comment]
BTW: You should update the translation link in section E.2.4:
https://l10n.opensuse.org/

**Comment by cb400f** [comment]
Yes, I host the repo. Isn't it working for you?

The link to l10n.opensuse.org is also updated on the 42.2 version.

**Comment by victorhck** [comment]
ah ok... I though it was a mistake! ;)
