### ISSUE TITLE
Update source code on GitHub

### ISSUE THREAD

**Issue by vinyanalista** [cb400f/opensuse-guide.org#5]
While working on my fork of openSUSE Guide (https://github.com/kamarada/guiadoopensuse), I realized this source code (https://github.com/cb400f/opensuse-guide.org) is not up-to-date compared to the website (http://opensuse-guide.org).

For instance, the file `images/pics/box.png` available on GitHub:

![box.png](https://github.com/cb400f/opensuse-guide.org/blob/master/images/pics/box.png?raw=true)

Is not the same presented on the website:

![box.png](http://opensuse-guide.org/images/pics/box.png)

Please, update the source code available on GitHub. Thank you!

**Comment by cb400f** [comment]
Thanks for the heads up. The files have been committed now. 

Thank you for translating the guide and thank you for your other suggestions. I'll be extremely busy for the next month or so. But after that I'll look closer into your suggestions.
