### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by CChalu** [cb400f/opensuse-guide.org#7]
Hello,
There is a broken link in section 3.4 The source code
The correct link is now:
http://download.opensuse.org/source/distribution/leap/15.0/repo/oss/src/
Thank you for your great job.
We hope to provide a French translation of the guide soon. :)

**Comment by victorhck** [comment]
Seems to work for me.
After the guide update, the new link seems to work properly
(IMHO The issue can be closed)
